### ISSUE TITLE
either configparser not installed , or SyntaxError

### ISSUE THREAD

**Issue by Huangdong2** [twisteroidambassador/ptadapter#1]
Downloading/unpacking https://pypi.python.org/packages/61/a7/48f627413200d5dfd0a5da8b494d34ccac03f8a87a6b2d765b7d81e175e
3/configparser-3.5.0b2.tar.gz
  Downloading configparser-3.5.0b2.tar.gz
  Running setup.py (path:/tmp/pip-GbaYGD-build/setup.py) egg_info for package from https://pypi.python.org/packages/61/a
7/48f627413200d5dfd0a5da8b494d34ccac03f8a87a6b2d765b7d81e175e3/configparser-3.5.0b2.tar.gz

Installing collected packages: configparser
  Running setup.py install for configparser

```
Skipping installation of /usr/local/lib/python2.7/dist-packages/backports/__init__.py (namespace package)
Installing /usr/local/lib/python2.7/dist-packages/configparser-3.5.0b2-nspkg.pth
```

Successfully installed configparser
Cleaning up...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pluggabletransportadapter/standalone_server.py", line 13, in <module>
    from pluggabletransportadapter import PluggableTransportServerAdapter
  File "/usr/local/lib/python2.7/dist-packages/pluggabletransportadapter/pluggabletransportadapter/**init**.py", line 1,
 in <module>
    from .baseserverclient import PluggableTransportServerAdapter, \
  File "/usr/local/lib/python2.7/dist-packages/pluggabletransportadapter/pluggabletransportadapter/baseserverclient.py",
 line 439
    buf = yield from reader.read(self.RELAY_BUFFER_SIZE)
                   ^
SyntaxError: invalid syntax

**Comment by twisteroidambassador** [comment]
Please use Python **3.4 or higher**. 2.7 is not supported.
