### ISSUE TITLE
IndexError when SMETHOD does not have 'options' field

### ISSUE THREAD

**Issue by JoeTester1965** [twisteroidambassador/ptadapter#3]
Hi.

Strange error. Works fine when using meek testing on localhost, but bombs out repeatedly (after a few seconds at most) when deploying meek on cloud platform. Have attached stderr output example.

Is this meek_client or wrapper issue?

Thanks
[example - worked for a while with meek.zip](https://github.com/twisteroidambassador/pluggabletransportadapter/files/692102/example.-.worked.for.a.while.with.meek.zip)

**Comment by twisteroidambassador** [comment]
Can't tell anything from the logs. It all comes from the meek executable; nothing by pluggabletransportadapter is in that log file.

Just guessing, did you copy a compiled meek executable to your cloud server? Try compiling it on the server itself.

**Comment by JoeTester1965** [comment]
Hi.

Still get this error when compiling both ends.

Sorry to forget this (is a part time pet project). but o get the server to run, I had to comment out this line in baseserverclient.py:

_self.transports[e[0]]["options"] = e[2]_

If I do not, get the following error:Traceback (most recent call last):
  File "./standalone_server.py", line 91, in <module>
    main_cli()
  File "./standalone_server.py", line 73, in main_cli
    server.start()
  File "/home/ubuntu/Play/pluggabletransportadapter/pluggabletransportadapter/baseserverclient.py", line 203, in start
    if self.parse_stdout(line.strip()): break
  File "/home/ubuntu/Play/pluggabletransportadapter/pluggabletransportadapter/baseserverclient.py", line 243, in parse_stdout
    self.transports[e[0]]["options"] = e[2]
IndexError: list index out of range

Could this be something to do with it?

**Comment by JoeTester1965** [comment]
Finally stable.

Used meek-client and meek-server from https://people.debian.org/~infinity0/apt/ 

Rather than using https://github.com/arlolra/meek 

Wish I knwe what the diffence was!

**Comment by twisteroidambassador** [comment]
Ah, yes, I believe you found a bug. The PT spec says:

    For each transport initialized, the PT proxy reports the listener
    status back to the parent via messages to stdout.

     SMETHOD <transport> <address:port> [options]
     [...]

       The OPTIONAL 'options' field is used to pass additional
       per-transport information back to the parent process.

Looks like the code does not handle the situation where the OPTIONAL 'options' field is not there. Will fix later.
