### ISSUE TITLE
--server does not auto-generate obfs4 keys (when removing predefined keys from config), error instead

### ISSUE THREAD

**Issue by sheksi** [twisteroidambassador/ptadapter#5]
In the current version, I run the program with 
`python3 ./standalone.py --server --verbose  ./standalone_server_config.ini`
with the recent version of obfs4proxy for TorBrowser.
The config file:

    [obfs4-options]
    iat-mode = 0
(In other words, the config options node-id, private-key, public-key, drbg-seed are left out, like the manual suggests.)

The program does not run, instead it produces error 
`future: <Future finished exception=PTExecSMethodError("SMETHOD-ERROR obfs4 missing argument 'node-id'",)>`

**Comment by twisteroidambassador** [comment]
Hmm. Try removing all options, including `iat-mode`. I think obfs4proxy will generate keys when no options at all are specified.

**Comment by sheksi** [comment]
Yes, that fixed it! Thank you.
Perhaps we should add a small note in the config file that all the options need to be hidden, because I think that neither the config file, nor the error message gave any hints to this.
