### ISSUE TITLE
CONF_FILE on Windows systems example

### ISSUE THREAD

**Issue by vainiya** [twisteroidambassador/ptadapter#9]
Can you show an example of CONF_FILE for Windows systems ?? Thanks for you work.

**Comment by twisteroidambassador** [comment]
Hi,

The only difference between a config file used on Windows and one used on Linux is paths. Just use Windows paths and you should be fine. For example, `C:\Users\username\Documents\obfs4proxy.exe` or whatever.

Do you have specific problems with using ptadapter on Windows?

**Comment by vainiya** [comment]
Hello. 
First, thanks for your response and for your work..
All is more dificult in Windows xDDD. 

In Windows everything needs a plus of configuration and to know well the shell of the system.  I have finally given up. 
On Linux ptadapter and other wrappers works like a charm. Obfs4proxy & Windows = Challenge

Communicating with obfs4proxy through environment variables is stupid. It should be possible to do everything with parameters. Although this is just my opinion.


Again, thank you very, very much. Really.


PD.- Can you close. Linux has been my solution (for now).
